CREATE TABLE producers (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(500),
	mobile VARCHAR(10),
	address VARCHAR(500),
	created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	is_deleted TINYINT(1) DEFAULT 0
) AUTO_INCREMENT = 1001;

CREATE TABLE movies (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(500),
	genre VARCHAR(100),
	length INT(4),
	year INT(4),
	synopsis VARCHAR(1000),
	price INT(4),
	producer INT,
	thumbnail VARCHAR(500),
	created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	is_deleted TINYINT(1) DEFAULT 0,
	FOREIGN KEY(producer) REFERENCES producers(id) ON DELETE CASCADE
) AUTO_INCREMENT = 1001;

CREATE TABLE actors (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(500),
	image VARCHAR(500),
	created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	is_deleted TINYINT(1) DEFAULT 0
) AUTO_INCREMENT = 1001;

CREATE TABLE movie_casts (
	movie INT,
	actor INT,
	PRIMARY KEY(movie, actor),
	FOREIGN KEY(movie) REFERENCES movies(id) ON DELETE CASCADE,
	FOREIGN KEY(actor) REFERENCES actors(id) ON DELETE CASCADE
);

CREATE TABLE customers (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(300),
	mobile VARCHAR(10),
	created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	is_deleted TINYINT(1) DEFAULT 0
) AUTO_INCREMENT = 1001;
